#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$application = require_once __DIR__.'/bootstrap/app.php';
$kernel = $application->make(Kernel::class, ['Laravel']);
$status = $kernel->handle(new ArgvInput);

exit($status);
